ClaseEF.ClasificadorAnimales.Web/Models/ErrorViewModel.cs
using System;

namespace ClaseEF.ClasificadorAnimales.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ClaseEF.ClasificadorAnimales.Web/Controllers/AnimalController.cs
using ClaseEF.ClasificadorAnimales.Data.EF;
using ClaseEF.ClasificadorAnimales.Servicios.Servicios.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace ClaseEF.ClasificadorAnimales.Web.Controllers
{
    public class AnimalController : Controller
    {
        ITipoAnimalServicio _tipoAnimalServicio;
        IAnimalServicio _animalServicio;
        public AnimalController(ITipoAnimalServicio tipoAnimalServicio, IAnimalServicio animalServicio)
        {
            _tipoAnimalServicio = tipoAnimalServicio;
            _animalServicio = animalServicio;
        }

        [HttpGet]
        public ActionResult Alta()
        {
            
            ViewBag.TipoAnimales = _tipoAnimalServicio.ObtenerTodos();

            return View();
        }

        [HttpPost]
        public ActionResult Alta(Animal animal)
        {
            if(!ModelState.IsValid && string.IsNullOrEmpty(Request.Form["OtroTipo"]))
            {
                ViewBag.TipoAnimales = _tipoAnimalServicio.ObtenerTodos();
                return View(animal);
            }
            //OPCIONAL, PARA AGREGAR UN TIPO DE ANIMAL QUE NO ESTE EN LA TABLA
            if(!string.IsNullOrEmpty(Request.Form["OtroTipo"]))
            {
                TipoAnimal nuevoTipoAnimal = new TipoAnimal() { Nombre = Request.Form["OtroTipo"] };
                _tipoAnimalServicio.Insertar(nuevoTipoAnimal);
                animal.IdTipoAnimal = nuevoTipoAnimal.IdTipoAnimal;
            }
            _animalServicio.Insertar(animal);
            return RedirectToAction("Lista");
        }

        [HttpGet]
        public ActionResult Lista()
        {
            ViewBag.TipoAnimales = _tipoAnimalServicio.ObtenerTodos();
            return View(_animalServicio.ObtenerTodos());
        }

        [HttpPost]
        public ActionResult Lista(int? IdTipoAnimal)
        {
            ViewBag.TipoAnimales = _tipoAnimalServicio.ObtenerTodos();

            if (IdTipoAnimal.HasValue)
            {
                return View(_animalServicio.ObtenerPorTipo(IdTipoAnimal.Value));

            }

            return View(_animalServicio.ObtenerTodos());
        }

        [HttpGet]
        public ActionResult Borrar(int id)
        {
            _animalServicio.borrar(id);
            return Redirect("/Animal/lista");
        }

    }
}

ClaseEF.ClasificadorAnimales.Web/Views/Animal/Alta.cshtml
@model ClaseEF.ClasificadorAnimales.Data.EF.Animal

<form action="/Animal/Alta" method="post">
    <div>
        Nombre:
        <input type="text" name="NombreEspecie"/>
    </div>
    <div>
        Peso:
        <input type="number" name="PesoPromedio"/>
    </div>
    <div>
        Edad:
        <input type="number" name="EdadPromedio"/>
    </div>
    <div>
        Tipo Animal:
        <select name="IdTipoAnimal">
            <option value="">Tipo Animal</option>
            @foreach (var tipoAnimal in (List<ClaseEF.ClasificadorAnimales.Data.EF.TipoAnimal>) ViewBag.TipoAnimales)
           {
               <option value="@tipoAnimal.IdTipoAnimal">@tipoAnimal.Nombre</option>
           }
        </select>
    </div>            
    <!-- OPCIONAL, PARA AGREGAR UN TIPO DE ANIMAL QUE NO ESTE EN LA TABLA -->
    <input type="text" name="OtroTipo" value="" />
    <!-- OPCIONAL, PARA AGREGAR UN TIPO DE ANIMAL QUE NO ESTE EN LA TABLA -->
    <div>
        <input type="submit" value="Guardar"/>
    </div>
</form>

ClaseEF.ClasificadorAnimales.Web/Views/Animal/Lista.cshtml
@model List<ClaseEF.ClasificadorAnimales.Data.EF.Animal>
<form action="/animal/lista" method="post">
    <div>
        Tipo Animal:
        <select name="IdTipoAnimal">
            <option value="">Tipo Animal</option>
            @foreach (var tipoAnimal in (List<ClaseEF.ClasificadorAnimales.Data.EF.TipoAnimal>) ViewBag.TipoAnimales)
           {
               <option value="@tipoAnimal.IdTipoAnimal">@tipoAnimal.Nombre</option>
           }
        </select>
        <input type="submit" name="Filtrar" value="Filtrar" />
    </div>

    <table>
        <tr>
            <th>NOMBRE</th>
            <th>PESO(KG)</th>
            <th>EDAD(AÑOS)</th>
            <th>TIPO</th>
            <th>BORRAR</th>
        </tr>
        @foreach (var animal in Model)
       {
           <tr>
               <td>@animal.NombreEspecie</td>
               <td>@animal.PesoPromedio</td>
               <td>@animal.EdadPromedio</td>
               <td>@animal.IdTipoAnimalNavigation.Nombre</td>
               <td><a href="/Animal/borrar/@animal.IdAnimal">Borrar</a></td>
           </tr>
       }
    </table>
</form>

ClaseEF.ClasificadorAnimales.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ClaseEF.ClasificadorAnimales.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClaseEF.ClasificadorAnimales.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ClaseEF.ClasificadorAnimales.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animal" asp-action="Alta">Alta Animal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animal" asp-action="Lista">Animales</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ClaseEF.ClasificadorAnimales.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>